import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { MenuProvider } from "@/contexts/menuContext";
import MenuOverlay from "@/components/menu/MenuOverlay";

const neueHaasGrotesk = localFont({
  src: [
    {
      path: "../../public/fonts/nHaasGrotDisp/NeueHaasGrotDisp-55Roman.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/nHaasGrotDisp/NeueHaasGrotDisp-65Medium.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/nHaasGrotDisp/NeueHaasGrotDisp-75Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-neue-haas-grotesk-display-pro",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${neueHaasGrotesk.variable} relative antialiased`}>
        <MenuProvider>
          <MenuOverlay />
          <Navbar />
          {children}
          <Footer />
        </MenuProvider>
      </body>
    </html>
  );
}
